### ISSUE TITLE
Problemas con archivo .gitignore

### ISSUE THREAD

**Issue by ArnoldoRicardo** [ajamaica/Api-REST-del-Congreso#4]
En el repositorio tienes archivos de configuraciones de tu explorador de archivos, que no tienen caso tenerlos en el control de vercion
![instantnea20](https://f.cloud.github.com/assets/1000317/1101383/44e235e2-17c4-11e3-8766-a6cad49fc6aa.png)

**Comment by ArnoldoRicardo** [comment]
si por que no, son archivos innecesarios que podrían crear conflictos

**Comment by krescruz** [comment]
Resuelto, gracias @anymex  fixes #5
